### PR TITLE
Create Hotas.starconflict.amgp

### PR DESCRIPTION
**Pull request by Fr-Dae**
2e try to push this x)

### CODE REVIEW

**Comment by pktiuk** [comment]
Almost good, but you forgotten about directory `03000000a30600006207000011010000`  in:
`applications -> StarConflict -> 03000000a30600006207000011010000 -> Hotas.amgp`   
Is there any difference between steam version of `StarConflict` and non-steam? Hoes it have to marked as a steam version?

**Comment by Fr-Dae** [comment]
it's all made plausible that I forgot a bunch of things, that's exactly why I asked you for your help twice, I absolutely don't understand the logic of how github works (and that doesn't really interested in addition)

however I have some knowledge base on gnu_linux lubuntu: /

I only played the steam / protron version (a home version of wine supplied by steam) and therefore an extra overlay.

I have ABSOLUTELY no idea whether or not there is a difference with the non-steam version, that's why I specified it "just in case"

if you see something corrected you have my full agreement you seem to know more what you are doing than me x)

as long as the image is displayed correctly as a visual aid and the profiles it is the main
and yes the joystick is not mapped because it is currently unplayable with.

maybe later i will manage to have a similar configuration to the smile where the devs will stick their fingers out of the ass. (not you, you are great;))

what the number do ?
i try upload my folder/file with web version of github

**Comment by Fr-Dae** [comment]
I hadn't created a folder containing the profiles and the image? or did it crash? 

https://i.imgur.com/M18bJfu.jpg
LD0002843425

**Comment by pktiuk** [comment]
> it's all made plausible that I forgot a bunch of things, that's exactly why I asked you for your help twice, I absolutely don't understand the logic of how github works (and that doesn't really interested in addition)

If you want we can merge it as it is and I will add what I need here later. I think it will be quicker and easier for both of us.

**Comment by Fr-Dae** [comment]
ok ! thanks you bro

**Pull request merged**
