### PR TITLE
Create StarConflict (steam)

### PR DESCRIPTION
**Pull request by Fr-Dae**
hotas.joystick.amgp

### CODE REVIEW

**Comment by Fr-Dae** [comment]
[https://i.imgur.com/yDE2rMS.png](url)
[https://i.imgur.com/InRsFG4.jpeg](url)

**Comment by Fr-Dae** [comment]
https://i.imgur.com/M18bJfu.jpg
one image

**Comment by pktiuk** [comment]
@Daebis 
This config was ok, but there was a mistake.
This config should be placed in `applications -> StarConflict -> 03000000a30600006207000011010000 -> controller.name.amgp`

**Comment by Daebis** [comment]
could you fixe that please ? i don't expert for add folder on github

**Comment by Fr-Dae** [comment]
i think i have find how to push folder and image, could you valided it please ?

**Comment by Fr-Dae** [comment]
@pktiuk

**Pull request merged**
